#!/bin/bash

ogr2ogr $1.shp -sql "$5" PG:"$6"

gdal_rasterize -a r -of gtiff -a_nodata 0 -tr $3 $4 $1.shp $1.r.tif
gdal_rasterize -a g -of gtiff -a_nodata 0 -tr $3 $4 $1.shp $1.g.tif
gdal_rasterize -a b -of gtiff -a_nodata 0 -tr $3 $4 $1.shp $1.b.tif

gdalbuildvrt -separate $1.vrt $1.r.tif $1.g.tif $1.b.tif

gdal_translate -ot Byte -r bilinear -colorinterp red,green,blue -co TILED=YES -co COMPRESS=LZW -co BIGTIFF=IF_SAFER $1.vrt $1

rm $1.*